
service: riskalyze-gottogo

custom:
  webpackIncludeModules: true
  dotenv:
    path: .env
    include:
      - DYANMODB_TABLE
      - R_AWS_REGION
      - R_AWS_KEY
      - R_AWS_SECRET
      - AUTH_TOKEN
      - SLACK_TOKEN

provider:
  name: aws
  runtime: nodejs6.10
  profile: devServerless
  region: us-west-2
  stage: dev

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  auth:
    handler: handler.auth
  getAllStatuses:
    handler: handler.getAllStatuses
    events:
      - http:
          path: status
          method: GET
          cors: true
          integration: lambda
  getStatusById:
    handler: handler.getStatusById
    events:
      - http:
          path: status/{id}
          method: GET
          cors: true
          integration: lambda
  createStatus:
    handler: handler.createStatus
    events:
      - http:
          path: status
          method: POST
          cors: true
          integration: lambda
  slackStatus:
    handler: handler.slackStatus
    events:
      - http:
          path: status/slack
          method: POST
          cors: true
          integration: lambda
  slackStatusNotify:
    handler: handler.slackStatusNotify
    events:
      - http:
          path: status/slack/notify
          method: POST
          cors: true
          integration: lambda