
service: riskalyze-gottogo

custom:
  webpackIncludeModules: true
  dotenv:
    path: .env
    include:
      - DYANMODB_TABLE
      - AWS_REGION
      - AWS_KEY
      - AWS_SECRET
      - AUTH_TOKEN

provider:
  name: aws
  runtime: nodejs6.10
  profile: inractiveServerless
  region: us-west-2
  stage: dev

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  auth:
    handler: handler.auth
  getAllStatuses:
    handler: handler.getAllStatuses
    events:
      - http:
          path: status
          method: GET
          cors: true
          integration: lambda
          authorizer: auth
  getStatusById:
    handler: handler.getStatusById
    events:
      - http:
          path: status/{id}
          method: GET
          cors: true
          integration: lambda
          authorizer: auth
  createStatus:
    handler: handler.createStatus
    events:
      - http:
          path: status
          method: POST
          cors: true
          integration: lambda
          authorizer: auth