
service: inractive-api-user

provider:
  name: aws
  runtime: nodejs6.10
  profile: inractiveServerless
  region: us-west-2
  stage: dev

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

functions:
  getAllStatuses:
    handler: handler.getAllStatuses
    vpc:
      securityGroupIds:
        - sg-0a3b2b5396c02d4bc
      subnetIds:
        - subnet-17e7265c
        - subnet-e4ea69be
        - subnet-1bf65062
    events:
      - http:
          path: status
          method: GET
          cors: true
          integration: lambda
  getStatusById:
    handler: handler.getStatusById
    vpc:
      securityGroupIds:
        - sg-0a3b2b5396c02d4bc
      subnetIds:
        - subnet-17e7265c
        - subnet-e4ea69be
        - subnet-1bf65062
    events:
      - http:
          path: status/{id}
          method: GET
          cors: true
          integration: lambda
  createStatus:
    handler: handler.createStatus
    vpc:
      securityGroupIds:
        - sg-0a3b2b5396c02d4bc
      subnetIds:
        - subnet-17e7265c
        - subnet-e4ea69be
        - subnet-1bf65062
    events:
      - http:
          path: status
          method: POST
          cors: true
          integration: lambda
